sonar.projectKey=xaverric_leaderborder
sonar.organization=xaverric
sonar.projectName=leaderborder

sonar.sources=packages/client/src,packages/worker/src,packages/worker/public/js,scripts
sonar.tests=packages/client/test,packages/worker/test
sonar.test.inclusions=**/*.test.js,**/*.e2e.js
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/out/**,scripts/*.test.js

sonar.javascript.file.suffixes=.js,.cjs,.mjs
sonar.sourceEncoding=UTF-8
